### PR TITLE
fixed problem on using parameters without secret

### PR DESCRIPTION
**Pull request by ochanje210**
Without secret, the request url missed `?` and resulted 404 response when there are parameters.
Here, I have tried to fix it in simple way by adding `?` to url directly.

### CODE REVIEW

**Comment by marckrenn** [comment]
Thanks!

**Comment by ochanje210** [comment]
I should have tested enough for the previous PR. X(

**Comment by marckrenn** [comment]
No problem, I didn't notice it either as I rarely use parameters myself.

I think the last time I used it was to write a sequential loader to load large structures (containing base64-encoded images) on an one-by-one basis. Maybe I'll add it to the demo projects with the next update 👍

**Comment by marckrenn** [comment]
Not so fast! :)
Just noticed that your PR breaks compatibility with firebase.secret, so I had to revert it. Seems like the request query is missing the question mark when using secret. Could you look into this problem by using one of my demo files (e.g. [this one](https://framer.cloud/ljPWN/))? Thanks.

**Pull request merged**
